name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8c65c7b3cd5cd95869c3d7a2fe5e79f16e6736dc6fd1afed8c20b5267af4bf"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
datapack-folder = "./global_packs/required_data"
